### ISSUE TITLE
[Feature Request] 建议为 nexttrace 增加自定义 DNS 递归服务器的选项

### ISSUE THREAD

**Issue by SunBK201** [OwO-Network/nexttrace-enhanced#11]
存在自定义 DNS 递归服务器的需求，目前 nexttrace 貌似 DNS 解析使用的是 CGo 的 `getaddrinfo` ? 目前如果要自定义 DNS 服务器需要修改操作系统 DNS，灵活性较差，建议增加自定义 DNS 递归服务器的选项同时使用 `pure-Go DNS resolver` 进行 DNS 解析。

**Comment by sjlleo** [comment]
我没记错的话，如果在运行不指定环境变量 `GODEBUG=netdns=Cgo+2` ，编译时指定 `CGO_ENABLED=0` （方便交叉编译）的情况下，应该默认使用的是 `Pure-Go`（这里面我之前有在书里看到存在一个优先级的关系，没深入了解过啦，有错的话欢迎指正~），运行时默认会从 `resolver.conf` 去获取 DNS IP。
不过我记得的话 `getaddrinfo()` 好像是只支持IPv4的吧qwq，默认Go的`LookupIP`能返回 IPv6，总感觉在缺省下是用 `Pure-Go` 做的解析。
```Go
// LookupIP looks up host using the local resolver.
// It returns a slice of that host's IPv4 and IPv6 addresses.
func LookupIP(host string) ([]IP, error) {
	addrs, err := DefaultResolver.LookupIPAddr(context.Background(), host)
	if err != nil {
		return nil, err
	}
	ips := make([]IP, len(addrs))
	for i, ia := range addrs {
		ips[i] = ia.IP
	}
	return ips, nil
}
```

**Comment by sjlleo** [comment]
我等会儿好好研究一下这个问题，另外把指定DNS解析的功能加上

**Comment by sjlleo** [comment]
36052bf 已经并随 [v0.2.1-beta.6](https://github.com/OwO-Network/nexttrace-enhanced/tree/v0.2.1-beta.6) 一起发布了，使用 `-dns 1.1.1.1` 试试 
By the way, 我想它应该是 `--dns`，但是 flag 参数包能提供的非常有限，这点在后面版本会进行重构。

**Comment by SunBK201** [comment]
> [36052bf](https://github.com/OwO-Network/nexttrace-enhanced/commit/36052bf20c0bc9c3335a4b962d9e6b2887fe0819) 已经并随 [v0.2.1-beta.6](https://github.com/OwO-Network/nexttrace-enhanced/tree/v0.2.1-beta.6) 一起发布了，使用 `-dns 1.1.1.1` 试试
> By the way, 我想它应该是 `--dns`，但是 flag 参数包能提供的非常有限，这点在后面版本会进行重构。

working well! Thanks~
