### ISSUE TITLE
[Bug] Linux 一键安装脚本 bash: /dev/fd/63: No such file or directory

### ISSUE THREAD

**Issue by SunBK201** [OwO-Network/nexttrace-enhanced#12]
Ubuntu 20.04 LTS
`sudo bash <(curl -Ls https://raw.githubusercontent.com/OwO-Network/nexttrace-enhanced/main/nt_install.sh)`

报错：`bash: /dev/fd/63: No such file or directory`

**Comment by sjlleo** [comment]
试试这样，```sudo bash < <(curl -Ls https://raw.githubusercontent.com/OwO-Network/nexttrace-enhanced/main/nt_install.sh)```

**Comment by SunBK201** [comment]
> 试试这样，`sudo bash < <(curl -Ls https://raw.githubusercontent.com/OwO-Network/nexttrace-enhanced/main/nt_install.sh)`

有效

**Comment by sjlleo** [comment]
刚刚在路上，对这个问题没能回复详全，这里在补充一下吧~

这个问题通常出现在用户登录时以普通用户（非 root）运行，但是在需要用 sudo 提权时，或者使用 chroot，就会报 `bash: /dev/fd/63: No such file or directory`。
在正常情况下，通过 `<(command A)`  运行命令的输出会被系统以匿名管道的形式暂时保存在 `/dev/fd/63` 内，然后 bash 会以 sudo 权限读取 command A 的输出（`/dev/fd/63`）作为一个可执行的脚本文件来运行，但是普通用户中并没有`root`用户的目录，就会导致这个错误。
解决办法我倒是想到了几个，核心思想就是避开 bash 直接通过 `/dev/fd/63` 读取、执行脚本文件。
1. `sudo bash < <(curl -Ls https://raw.githubusercontent.com/OwO-Network/nexttrace-enhanced/main/nt_install.sh)`
   原理是把curl的内容输出到 `/dev/fd/63` 以后，再通过输入重定向传给 bash，这样 bash 就不会直接读取`/dev/fd/63`的文件了。
2. `sudo bash -c "$(curl -Ls https://raw.githubusercontent.com/OwO-Network/nexttrace-enhanced/main/nt_install.sh)"`
   直接不使用 `<()` 进程替换，而使用 bash `-c` 参数来直接获取 curl 下来的内容并运行

如有错误请指正~

**Comment by sjlleo** [comment]
另外，我突然发现，似乎用  `curl -Ls https://raw.githubusercontent.com/OwO-Network/nexttrace-enhanced/main/nt_install.sh | sudo bash` 会更简洁一点？

**Comment by SunBK201** [comment]
`sudo bash -c "$(curl -Ls https://raw.githubusercontent.com/OwO-Network/nexttrace-enhanced/main/nt_install.sh)"` 似乎是更常见的用法
