### ISSUE TITLE
Web API 希望即便是无响应的hop也能显示

### ISSUE THREAD

**Issue by isyekong** [OwO-Network/nexttrace-enhanced#14]
![image](https://user-images.githubusercontent.com/20068143/195384633-99a11bb6-4ec7-4822-a212-6c33be17ec52.png)
无回应的hop直接隐藏了感觉怪怪的，一开始还以为是丢失了。
希望依旧可以显示`***`
![image](https://user-images.githubusercontent.com/20068143/195385481-5bab19bb-5485-40cc-a546-8811fbc9138f.png)

**Comment by sjlleo** [comment]
4c66dcaabdea740c04ebcfe025fb8c75d863413f 应该现在没有问题了，记得先删掉 `~/.nexttrace/index.tmpl` 这个文件，然后在运行哦
