### ISSUE TITLE
Release中提供的Mips版本在我的Mips平台無法正常運行

### ISSUE THREAD

**Issue by Kongchenglige** [OwO-Network/nexttrace-enhanced#16]
## 你正在使用哪个版本的 nexttrace？

linux_mips 

## 你看到的异常现象是什么？

嘗試運行时出現
./nexttrace_linux_mips: line 1: syntax error: unexpected "("

CPU是MediaTek MT7628AN

system type		: MediaTek MT7628AN ver:1 eco:2
cpu model		: MIPS 24KEc V5.5

## 你期待看到的正常表现是怎样的？
正常運行

## 请附上你的命令
無法運行, 所以無法填寫

## 请附上出错时软件输出的错误信息
無法運行, 所以無法填寫

**Comment by sjlleo** [comment]
试试这个版本

https://github.com/OwO-Network/nexttrace-enhanced/releases/download/v0.2.1-beta.8-2/nexttrace_linux_mipsle

**Comment by Kongchenglige** [comment]
報錯： Illegal instruction
我認爲這可能是由於系統的原因
`root@OpenWrt:~# uname -an`
`Linux OpenWrt 5.4.188 #0 Sat Apr 16 12:59:34 2022 mips GNU/Linux`

**Comment by sjlleo** [comment]
感觉是 MT7628AN 缺失了一些指令集，之前有遇到过把新CPU 编译得到的二进制文件在旧 CPU 上面运行遇到报 `Illegal instruction`，这确实是一个很奇怪的问题。

这种情况下还是建议在 OpenWRT 上直接安装 Go，并 clone 源码到本地编译一下应该可以解决。

**Comment by Kongchenglige** [comment]
好的 謝謝！
