### ISSUE TITLE
公网IP的归属地有时会显示成LAN

### ISSUE THREAD

**Issue by Diffused7245** [OwO-Network/nexttrace-enhanced#22]
## 你正在使用哪个版本的 nexttrace？
NextTrace Enhanced v0.3.2-beta.1 2023-02-15T12:33:22Z 9c40f1f
用脚本`sudo bash -c "$(curl -Ls https://ghproxy.com/https://raw.githubusercontent.com/OwO-Network/nexttrace-enhanced/main/nt_install.sh)"`安装的。

系统版本：Linux pve 5.15.83-1-pve #1 SMP PVE 5.15.83-1 (2022-12-15T00:00Z) x86_64 GNU/Linux

## 你看到的异常现象是什么？
使用Nexttrace -f时，有时会把公网IP的归属地显示为LAN，随机出现此情况。

![image](https://user-images.githubusercontent.com/76898556/219287665-44542c27-d391-44e9-a8dc-88884a35a8ab.png)

## 你期待看到的正常表现是怎样的？
显示正确的归属地

## 请附上你的命令
nexttrace -f
1
1

## 请附上出错时软件输出的错误信息
无错误输出

**Comment by sjlleo** [comment]
已经修复，不过由于这个问题是后端导致的，所以不需要更新客户端。
