### ISSUE TITLE
brew 有问题

### ISSUE THREAD

**Issue by 0x0021** [OwO-Network/nexttrace-enhanced#3]
$brew tap OwO-Network/nexttrace                                                                       [21:27:27]
Running `brew update --auto-update`...
error: Not a valid ref: refs/remotes/origin/master
fatal: ambiguous argument 'refs/remotes/origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

**Comment by tsosunchia** [comment]
这个问题似乎是互联网连接出现问题导致的，下载中文件损坏了
您可以参看 [此链接](https://github.com/Homebrew/brew/issues/10368) 解决

**Comment by tsosunchia** [comment]
如有任何问题请回复，此issue将于24小时后关闭。
