### ISSUE TITLE
brew update错误

### ISSUE THREAD

**Issue by 0x0021** [OwO-Network/nexttrace-enhanced#7]
``` bash
owo-network/nexttrace-enhanced/nexttrace v0.1.10-beta.2 -> v0.1.11-beta.5
ca-certificates 2022-07-19 -> 2022-07-19_1
Error: go: undefined method `on_intel' for #<Resource:0x00007faba2171e20>
```

**Comment by sjlleo** [comment]
您好，

遇到这个问题，请您首先检查一下网络，brew 安装是编译安装，Go很多依赖是要到 `Google` 和 `Github` 上去下载的。
如果是国内不开 `TAP` 模式是不可能安装成功的，请检查 `brew` 终端能否正常打开 `Google`，或者直接下载 release 界面以及编译好的版本直接使用。

谢谢。

Best Regards,
Leo Shen

**Comment by tsosunchia** [comment]
另外麻烦您，提供一下操作系统版本以及系统架构，这样我才能更快帮您定位问题。

**Comment by 0x0021** [comment]
估计是 macos 13 beta版的bug，先不用管它了
