### ISSUE TITLE
请问有对线路分类做进一步支持的想法吗

### ISSUE THREAD

**Issue by LunreMore** [OwO-Network/nexttrace-enhanced#8]
开发组你们好,很感谢你们能够提供这么好的测试工具

同时我也观察到了测试结果中有骨干网的编号,所以想问一下开发组是否有完善骨干网名称的想法

例如这篇文章的分类 https://zhuanlan.zhihu.com/p/451683996

能够提供骨干网名称我觉得会使得工具更加便利一些

最后再次感谢开发组的便利工具

(如果有措辞不妥的地方还请原谅)

**Comment by sjlleo** [comment]
这篇文章就是我写的😂

您说的骨干网名称是指不显示T1骨干网的官网域名，而直接显示骨干网的名称，如 NTT 、Level3 吗？

如果可以的话，麻烦您举个例子，非常感谢。

**Comment by sjlleo** [comment]
您好，

感谢您的回复，我明白您说的是什么了，这是 IP Whois 信息，目前我联系的一个IP数据源有相关API可以调用，但是成本还是比较高的。

```json
{
	"ip": "221.183.89.34",
	"charge": "0.002USD",
	"status_code": "Success",
	"data": {
		"inetnum": "221.176.0.0 - 221.183.255.255",
		"netname": "CMNET",
		"country_code": "CN",
		"status": "ALLOCATED PORTABLE",
		"owner": "China Mobile Communications Corporation,Mobile Communications Network Operator in China,Internet Service Provider in China",
		"tech_info": {},
		"admin_info": {}
	},
}
```

**Comment by sjlleo** [comment]
> 哦哦这样啊大概理解了那还算了把,让开发者支付费用属实说不过去,期待工具越做越好.

我把您的建议进行了需公开的求调研，这个 TODO 呼声还是比较高的，在需求调研中很多朋友投了赞成票，认为是一个有用的功能，故正式立项了，尽管会导致成本进一步上升，但是为了更好的体验，我还是打算试着做一下。

因为初期并没有想到做这个，所以无论是后端的API还是客户端一些地方都要重新设计一下，可能会遇到很多Bug。

**Comment by sjlleo** [comment]
此 issue 在 Feature 未开发完成之前将持续保持打开状态，所有相关的问题反馈将通过此 issue 进行~

**Comment by sjlleo** [comment]
Surprise~

![图片](https://user-images.githubusercontent.com/13616352/186396249-2eb5f211-41c1-4851-8370-cb37d895b357.png)

大体工作已经完成了，您看看，对于这显示的格式还有什么值得商榷或者改进的地方吗？

**Comment by sjlleo** [comment]
57c8c7c3f61f5644e104be40c01b78c6af4094bd 修复了Modern模式下IPv6显示不整齐的问题，添加了 IPWhois 信息
欢迎下载 `v0.2.1-beta.1` 版本来尝鲜，如果喜欢我们的作品的话，也可以通过[爱发电](https://afdian.net/@sjlleo)来支持我们的持续开发，谢谢！

**Comment by sjlleo** [comment]
如果没有问题的话，我就关闭了哦，有问题欢迎提新issue~ qwq
