### ISSUE TITLE
[Feature Request] 希望 nexttrace 增加指定 src-ip 的选项

### ISSUE THREAD

**Issue by SunBK201** [OwO-Network/nexttrace-enhanced#9]
类似 ping 中的 -S 选项：src_addr, Use the following IP address as the source address in outgoing packets.

**Comment by SunBK201** [comment]
以及增加指定出站网卡的选项

**Comment by sjlleo** [comment]
Good Idea!
我争取这2天就加上这个 feature = =

**Comment by SunBK201** [comment]
thanks~ 🎉

**Comment by sjlleo** [comment]
有个关于这个 Feature 的特性想和您一起探讨一下哦
我在思考，要不要专门再加个参数，罗列当前所有可用网卡，让用户自行来选择，比如这样~

![图片](https://user-images.githubusercontent.com/13616352/187064370-4bc163c2-f418-443a-91d4-c82246838d55.png)

**Comment by SunBK201** [comment]
> 有个关于这个 Feature 的特性想和您一起探讨一下哦 我在思考，要不要专门再加个参数，罗列当前所有可用网卡，让用户自行来选择，比如这样~
> 
> ![图片](https://user-images.githubusercontent.com/13616352/187064370-4bc163c2-f418-443a-91d4-c82246838d55.png)

可以加入指定网卡的选项，但是列出网卡的选项 `ifconfig` 已经足够了，我认为 nexttrace 要做的是尽可能让用户可以指定 `ifconfig` 中列出的任意网卡。

**Comment by sjlleo** [comment]
> 可以加入指定网卡的选项，但是列出网卡的选项 `ifconfig` 已经足够了，我认为 nexttrace 要做的是尽可能让用户可以指定 `ifconfig` 中列出的任意网卡。

好诶，加这个功能其实超快的说（当时就有考虑到，只是被我手动填成了 0.0.0.0 直接监听全局了qwq

**Comment by SunBK201** [comment]
因为有些用户可能机器上有多块网卡（包括虚拟网卡），所以增加 指定 src-ip 和 网卡 的选项是必要的

**Comment by sjlleo** [comment]
> 因为有些用户可能机器上有多块网卡（包括虚拟网卡），所以增加 指定 src-ip 和 网卡 的选项是必要的

我发布了一个`0.2.1-beta.3`版本，现在可以使用 -S 指定 Source IP，指定网卡还没有实装，您可以测试一下各功能是否工作正常哦，谢谢！

**Comment by SunBK201** [comment]
> > 因为有些用户可能机器上有多块网卡（包括虚拟网卡），所以增加 指定 src-ip 和 网卡 的选项是必要的
> 
> 我发布了一个`0.2.1-beta.3`版本，现在可以使用 -S 指定 Source IP，指定网卡还没有实装，您可以测试一下各功能是否工作正常哦，谢谢！

it works! 🎉

**Comment by sjlleo** [comment]
现在指定网卡名称的参数也应该正常工作了，使用 `-D` 参数试试，如 `-D en1`

**Comment by SunBK201** [comment]
> 现在指定网卡名称的参数也应该正常工作了，使用 `-D` 参数试试，如 `-D en1`

works, good job! 👍

**Comment by SunBK201** [comment]
`-S` `-D` 似乎对于 `-f` 快速测试模式不生效？

**Comment by sjlleo** [comment]
> @sjlleo `-S` `-D` 似乎对于 `-f` 快速测试模式不生效？

我的锅，马上就修
